language: python
python:
    - "2.7"
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
install:
    - pip install -r requirements/test.txt
    - pip install coveralls
script: make validate
branches:
    only:
        - master
after_success:
    coveralls
